version: '3.9'

services:
  app:
    image: bitnami/laravel:12
    ports:
      - '${APP_PORT:-8000}:8000'
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - DB_DATABASE=${DB_DATABASE:-mekodoniya7979}
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: '${DB_DATABASE:-mekodoniya7979}'
      POSTGRES_USER: '${DB_USERNAME:-postgres}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-password}'
    ports:
      - '54320:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
